services:
  db:
    image: tgrochowski87/cookbook-db-dev-amd64
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./database/db.env
    volumes:
      - /var/lib/postgresql/data

  api:
    image: tgrochowski87/cookbook-api-amd64
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./api/appsettings.json:/app/appsettings.json
    depends_on:
      - db

  web:
    image: tgrochowski87/cookbook-web-amd64
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./web/nginx.conf:/etc/nginx/nginx.conf
      - ./web/config.js:/usr/share/nginx/html/config.js
    depends_on:
      - api

  prometheus:
    image: prom/prometheus:v3.0.1
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/web.yml:/etc/prometheus/web.yml
      - ./prometheus/data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    depends_on:
      - api

  loki:
    image: grafana/loki:3.3.0
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/loki
    depends_on:
      - api

  grafana:
    image: grafana/grafana:11.3.1
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    env_file:
      - ./grafana/grafana.env
    depends_on:
      - api
      - loki
      - prometheus
